version: 1.0

outputPath: "./data/dataset.csv"
dumpPath: "./simplewiki-20240420-pages-articles.xml"
remote:
  dataset: "StabilitySharedBarrett/CleanWikiDumps"
  trainData: "randSample24000PagesCleanedWikiDump20240420.csv"
  testData: "responsesQnA5000sampleSetWikiDump20230420.csv"
prompt:
  template: 
    "You are a teacher creating a test for students about {topic}. Create 3 concise questions about {topic} using the Article below. Write 4 answer choices. Write the correct answer. Questions and answers must be less than 20 words each.\n
    ##\n
    Article: '''{context}'''\n
    ##\n
    Test Questions about {topic}: 
    "
  topic: "{topic}"
parameters:
  model: "stabilityai/stablelm-2-1_6b"
  maxTokens: 2048
  minTokens: 256
  maxNewTokens: 128
  temperature: 0.6
  topP: 0.7
  topK: 10
  typicalP: 0.5
  minP: 0.2
  repetitionPenalty: 1.3
  doSample: True
  numBeams: 1
classifier:
  model: "HuggingFaceTB/fineweb-edu-classifier"
debug:
  printResults: False
  pageLimiter: 6
  randSample: 99 # x% of pages get randomly selected to process

